[package]
name = "xtnd-base"
default-run = "xtnd"
version = "0.1.0"

[dependencies]
ctor = "0.1.21"
libc = "0.2.111"
dirs = "4.0.0"
libloading = "0.7"

[lib]
name = "xtnd_loader"
crate-type = ["dylib"]
path = "lib/src/lib.rs"

[[bin]]
name = "xtnd"
path = "cli/src/main.rs"