[package]
name = "xtnd"
default-run = "xtnd-cli"
version = "0.1.0"

[dependencies]
ctor = "0.1.21"
libc = "0.2.111"

[lib]
name = "xtnd_lib"
crate-type = ["dylib"]
path = "lib/src/lib.rs"

[[bin]]
name = "xtnd-cli"
path = "cli/src/main.rs"