[package]
name = "xtnd-cli"
version = "0.1.0"
edition = "2021"
default-run = "xtnd"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "xtnd"
path = "src/main.rs"

[dependencies]
